[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "apache-airflow",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "ruff>=0.11.2",
]
